volumes:
  portrainer_data:
    name: portrainer_data

services:
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr
    ports:
      - "8787:8787"
    environment:
      - PUID=1000
      - PGID=1000 - UMASK=002
      - TZ=Europe/Kyiv
    volumes:
      - /docker/appdata/readarr/config:/config
      - /data/media/library/books:/data/media/library/books

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portrainer_data:/data

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      # - LOG_LEVEL=debug
      - TZ=Europe/Kyiv
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /docker/appdata/overserr/config:/app/config
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /docker/appdata/plex:/config
      - /data/media/library/tvshows:/data/media/library/tvshows
      - /data/media/library/movies:/data/media/library/movies
    group_add:
      - "104"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=0002
      - TZ=Europe/Kyiv
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /docker/appdata/qbittorrent/appdata:/config
      - /data/media/torrents:/data/media/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:release
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Kyiv
    volumes:
      - /docker/appdata/prowlarr:/config

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /data:/data

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /data:/data

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /docker/appdata/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Kyiv

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/appdata/homarr/configs:/app/data/configs
      - /docker/appdata/homarr/icons:/app/public/icons
      - /docker/appdata/homarr/data:/data
    ports:
      - 7575:7575

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - 8887:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:10.11.0-rc3
    container_name: jellyfin
    volumes:
      - /docker/appdata/jellyfin/config:/config
      - /docker/appdata/jellyfin/cache:/cache
      - /data/media/library/tvshows:/data/media/library/tvshows
      - /data/media/library/movies:/data/media/library/movies
    restart: unless-stopped
    network_mode: host
    group_add:
      - "104"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    ports:
      - 51820:51820/udp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
      - SERVERURL=${PUBLIC_IP}
      - PEERDNS=192.168.3.1 # Set to your router, or your local DNS server
      - SERVERPORT=51820
      - PEERS=phone,laptop
      - ALLOWEDIPS=192.168.3.0/24 # Set your local network address range
      - INTERNAL_SUBNET=192.168.4.0/24 # Be sure that it is not intersect with you REAL local subnetwork range
    volumes:
      - /docker/appdata/wireguard/config:/config
      - /lib/modules:/lib/modules

  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    restart: unless-stopped
    ports:
      - "9705:9705"
    volumes:
      - /docker/appdata/huntarr:/config
    environment:
      - TZ=Europe/Kyiv

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Kyiv
    ports:
      - "8191:8191"
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - /docker/appdata/filebrowser:/config
      - /:/srv
    environment:
      - TZ=Europe/Kyiv
      - PUID=1000
      - PGID=1000
      - UMASK=0002
